### ISSUE TITLE
price streaming crashes occassionally

### ISSUE THREAD

**Issue by quantverse** [lteacher/simple-fxtrade#17]
Hello,

I am testing your great wrapper, it works very nice except from one issue - streaming prices causes a crash occasionally (especially when there are issues with the network). Getting this error message:

```
app_1_49ccf84303d3 |     SyntaxError: Unexpected end of JSON input
app_1_49ccf84303d3 |     at JSON.parse (<anonymous>)
app_1_49ccf84303d3 |     at IncomingMessage.<anonymous> (/botmate/node_modules/simple-fxtrade/dist/node.js:7:31009)
app_1_49ccf84303d3 |     at emitOne (events.js:116:13)
app_1_49ccf84303d3 |     at IncomingMessage.emit (events.js:211:7)
app_1_49ccf84303d3 |     at addChunk (_stream_readable.js:263:12)
app_1_49ccf84303d3 |     at readableAddChunk (_stream_readable.js:250:11)
app_1_49ccf84303d3 |     at IncomingMessage.Readable.push (_stream_readable.js:208:10)
app_1_49ccf84303d3 |     at HTTPParser.parserOnBody (_http_common.js:137:22)
app_1_49ccf84303d3 |     at TLSSocket.socketOnData (_http_client.js:454:20)
app_1_49ccf84303d3 |     at emitOne (events.js:116:13)
```

Disregard the `app_1_49ccf84303d3` part (the application runs in a container). It seems the library is trying to parse incomplete messages some times.

Using node.js `8.14.0`...

**Comment by lteacher** [comment]
Hmm sorry damn i have some issues getting notifications on this repo I think i accidentally unwatched some time back due to org spam that was later resolved by some github feature.

I'll see if I can take a look at it soon. Its probably just this like over here:
https://github.com/lteacher/simple-fxtrade/blob/0f43966589fef8e780500aacbba998f16c5aefc9/lib/subscription.coffee#L15

But i guess it could be somewhere else since that is a random guess without even checking at all.

**Comment by lteacher** [comment]
Probably its fixed in latest version (1.1.5) if you want to let me know if you get that issue anymore. Cheers

**Comment by quantverse** [comment]
Hello,

thanks for your answer!

At the end I have created my own "micro-library" for streaming Oanda prices because I needed production quality code ASAP. There were two problems I had to focus on:

* I needed to `try/catch` the exception if JSON parsing fails in order to prevent crashing the whole node app (I cannot rely on what I get from Oanda servers here)
* **sometimes there are more than one(!) JSON texts in the buffer, so I needed to split it by CR/LF and parse every part separately (often this can take considerable time before this happens)**

My code for inspiration:

```javascript
'use strict';

const request = require('request');
const util = require('util');
const querystring = require('querystring');
const EventEmitter = require('events');
const moment = require('moment');
const debug = require('debug')('oanda');

class OandaStream extends EventEmitter {
    constructor(accountId, token, instruments) {
        super();
        this.token = token;
        const instr = querystring.stringify({ instruments: instruments.join(',')});
        this.url = util.format('https://stream-fxtrade.oanda.com/v3/accounts/%s/pricing/stream?%s', accountId, instr);
    }

    subscribe() {
        const self = this;
        debug("suscribing to:", self.url);
        request(this.url, {
            'timeout': 30000,
            'auth': {
                'bearer': self.token
            }
        }, function (error, response, body) {
            debug('end of stream detected:', error, (response) ? response.statusCode : 'n/a', body);
            setTimeout(self.subscribe.bind(self), 10000); // retry in 10 seconds

        }).on('data', function(data) {
            // decompressed data as it is received
            //console.log(data.toString('utf8'));
            const ar = data.toString('utf8').split(/\r?\n/);
            ar.forEach(function(x) {
                if (x === '') return; // skip empty string
                let obj = null;
                try {
                    obj = JSON.parse(x);
                } catch (e) {
                    return; // silent fail
                }
                if (obj === null) return; // skip
                if (obj.type === 'PRICE') {
                    //debug(data);
                    self.emit('quote', {
                        instrument: obj.instrument,
                        ask: (obj.asks.length) ? parseFloat(obj.asks[0].price) : null,
                        bid: (obj.bids.length) ? parseFloat(obj.bids[0].price) : null,
                        time: moment(data.time),
                        tradeable: obj.tradeable
                    });

                } else if (obj.type === 'HEARTBEAT') {
                    self.emit('heartbeat', {time: moment(obj.time)})

                } else {
                   debug('unexpected response:', data.toString('utf8'));
                }

            });


        }).on('error', function(err) {
            debug('error:', err);
        });
    }
}

module.exports = OandaStream;
```

**Comment by lteacher** [comment]
Ok ill close this issue for now then and if anyone has the issue (after the fix i did) they can reopen.

This package just wraps the api. I dont use the price stream because where i used this i sync numerous candles by smashing get requests with certain intervals and then i store the data in db. When the db changes with my shape and logic to deal with the various lame nuances that relate to how data is returned from Oanda then I have another app running strategies which respond to the db events. So that is why I wasn't aware of the stream problem.

I have placed orders and closed positions etc as well as syncing all that data for backtesting and works fine for me, regarding all the rest of the package.

Cheers

**Comment by quantverse** [comment]
If I will have some extra time I will fix your code the same way as in my example and submit a PR...

**Comment by lteacher** [comment]
Hmm well I wont be implementing any of the shape related logic from above and not using request either as that will not work in browser, however, since I havent been using the stream as mentioned its possible I missed the part you mentioned above about the multiple entries in the buffer and that problem would still be there which would not be acceptable for me.

Ill run the stream and do some checking when time permits today and if there are messages being missed in the buffer or failures in parsing due do what I would expect to be a JSON syntax error for invalid token then Ill make changes to resolve that issue.

**Comment by quantverse** [comment]
Sure :) Just let the stream running for few hours and it will crash the app once there are multiple messages in the buffer..

**Comment by lteacher** [comment]
Do you have any examples for the message in 'unexpected response' from the code snippet? If that log statement occurs I would be very interested to know what is in that string.

**Comment by lteacher** [comment]
I wasn't able to get the issue after quite a few hours running the stream. Ill try over a longer period like 24 hrs but also pushed a PR to implement the splitting logic in case since it doesn't really impact anything anyway.

I did revisit my usage elsewhere and noted that actually this issue is in the subscription so it also would affect transactions and I did use that one extensively as its used for when your positions close or orders become open positions etc so you really have to use the transaction stream and I don't recall seeing the issue. I tried some disconnecting etc still didn't have it though so will try a bit more any probably still release the change anyway.

**Comment by lteacher** [comment]
During running over night after 6hrs I was able to observe the issue with multiple messages in the stream where there was then a parsing error even with current master

Different message though than this issue as expected from previous comments:

```
SyntaxError: Unexpected token { in JSON at position 266
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/lteacher/simple-fxtrade/dist/node.js:7:31422)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at IncomingMessage.Readable.push (_stream_readable.js:197:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
```

Will release the fix as it runs the unit tests provided for that scenario and then also run that one for a while to confirm.

**Comment by quantverse** [comment]
Hi,

unfortunately I don't have any example of the unexpected response case. I only had the example of multiple messages in the buffer, but you've already figured that out yourself...The main point is that the malformed JSON should never cause the software to crash...

**Comment by lteacher** [comment]
I have added some additional logic to handle any parse errors and released as a patch release.

Of course I just created this wrapper to suit my own requirements but i provided it as an open source package that anyone can use, however, it requires people such as yourself to collaboratively provide feedback or PRs for issues that I may not have encountered.

Certainly if any open source code is not at the production quality you require then you may want to implement your own solutions.

Thanks for reporting the issue!
